-- GENERATED by tools/gen_world.py. Room rectangles in world units, used for the room title toast.
return {
	{ id = "talks", title = "Talks & Podcast", x0 = -400.0, y0 = -272.0, x1 = 0.0, y1 = 0.0 },
	{ id = "open_source", title = "Open Source", x0 = 0.0, y0 = -272.0, x1 = 400.0, y1 = 0.0 },
	{ id = "games", title = "Games", x0 = -400.0, y0 = 0.0, x1 = 0.0, y1 = 272.0 },
	{ id = "about", title = "About & Contact", x0 = 0.0, y0 = 0.0, x1 = 400.0, y1 = 272.0 },
}
