components {
  id: "tilemap"
  component: "/main/room.tilemap"
  position {
    x: -208.0
    y: -144.0
    z: 0.0
  }
}
embedded_components {
  id: "walls"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"wall\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 0.0\n"
  "      y: -136.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"wall_0\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 0.0\n"
  "      y: 136.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "    id: \"wall_1\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -200.0\n"
  "      y: 0.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 6\n"
  "    count: 3\n"
  "    id: \"wall_2\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 200.0\n"
  "      y: 0.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 9\n"
  "    count: 3\n"
  "    id: \"wall_3\"\n"
  "  }\n"
  "  data: 208.0\n"
  "  data: 8.0\n"
  "  data: 10.0\n"
  "  data: 208.0\n"
  "  data: 8.0\n"
  "  data: 10.0\n"
  "  data: 8.0\n"
  "  data: 128.0\n"
  "  data: 10.0\n"
  "  data: 8.0\n"
  "  data: 128.0\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
