embedded_components {
  id: "floor"
  type: "sprite"
  data: "default_animation: \"floor\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "size {\n"
  "  x: 1920.0\n"
  "  y: 1280.0\n"
  "}\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/main.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "walls"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"wall\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 672.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"top\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -672.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "    id: \"bottom\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -992.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 6\n"
  "    count: 3\n"
  "    id: \"left\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 992.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 9\n"
  "    count: 3\n"
  "    id: \"right\"\n"
  "  }\n"
  "  data: 1024.0\n"
  "  data: 32.0\n"
  "  data: 10.0\n"
  "  data: 1024.0\n"
  "  data: 32.0\n"
  "  data: 10.0\n"
  "  data: 32.0\n"
  "  data: 640.0\n"
  "  data: 10.0\n"
  "  data: 32.0\n"
  "  data: 640.0\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
